//! Bounded observations used as Progress-TTL decision factors.
//!
//! This module owns recent-workload measurements and derived values only. It
//! does not own Program lifecycle state or make admission and pause decisions.

use std::collections::VecDeque;
use std::time::Instant;

/// One completed request used by capacity, fairness, and throughput estimates.
#[derive(Debug, Clone)]
pub struct RequestSample {
    /// Total prompt tokens observed at completion.
    pub prompt_tokens: usize,
    /// Completion tokens generated by the request.
    pub completion_tokens: usize,
    /// Prompt tokens served from prefix cache.
    pub cached_prompt_tokens: usize,
    /// Positive context delta from the Program's preceding request.
    pub context_growth_tokens: Option<usize>,
    /// Router-arrival to response-completion latency.
    pub e2e_seconds: f64,
    /// Decode duration when supplied by the backend.
    pub decode_seconds: Option<f64>,
    /// Time retained in the Program RequestPool before dispatch.
    pub queue_seconds: f64,
    /// Cache-continuous completed rounds since the latest TTL pause.
    pub rounds_since_ttl_pause: usize,
    /// Local monotonic request completion time.
    pub finished_at: Instant,
}

/// One same-Program interval paired with the prior request's miss impact.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ContinuitySample {
    /// Previous completion to next Router arrival interval.
    pub interval_seconds: f64,
    /// Estimated cost if the preceding context must be recomputed.
    pub cache_miss_impact_seconds: f64,
}

/// Fixed-size recent-workload windows maintained independently per DP rank.
#[derive(Debug, Default)]
pub struct ProgressTtlFactors {
    requests: VecDeque<RequestSample>,
    continuities: VecDeque<ContinuitySample>,
    ttl_pause_rounds: VecDeque<usize>,
}

impl ProgressTtlFactors {
    /// Append one completed request and evict the oldest sample at `limit`.
    pub fn push_request(&mut self, sample: RequestSample, limit: usize) {
        Self::push_bounded(&mut self.requests, sample, limit);
    }

    /// Append one interval sample and evict the oldest sample at `limit`.
    pub fn push_continuity(&mut self, sample: ContinuitySample, limit: usize) {
        Self::push_bounded(&mut self.continuities, sample, limit);
    }

    /// Append the cache-continuous rounds observed at one TTL pause.
    pub fn push_ttl_pause_rounds(&mut self, rounds: usize, limit: usize) {
        Self::push_bounded(&mut self.ttl_pause_rounds, rounds, limit);
    }

    fn push_bounded<T>(window: &mut VecDeque<T>, sample: T, limit: usize) {
        if limit == 0 {
            return;
        }
        if window.len() == limit {
            window.pop_front();
        }
        window.push_back(sample);
    }

    /// Whether request-derived estimates may replace their cold-start values.
    pub fn request_window_complete(&self, limit: usize) -> bool {
        limit > 0 && self.requests.len() >= limit
    }

    /// Whether interval-derived TTL fitting may replace its cold-start value.
    pub fn continuity_window_complete(&self, limit: usize) -> bool {
        limit > 0 && self.continuities.len() >= limit
    }

    /// Number of retained request samples.
    pub fn request_sample_count(&self) -> usize {
        self.requests.len()
    }

    /// Number of retained continuity samples.
    pub fn continuity_sample_count(&self) -> usize {
        self.continuities.len()
    }

    /// Number of retained segment-length samples captured by TTL pause.
    pub fn ttl_pause_sample_count(&self) -> usize {
        self.ttl_pause_rounds.len()
    }

    /// Mean positive Program context growth per completed request.
    pub fn average_context_growth_tokens(&self) -> f64 {
        Self::average(
            self.requests
                .iter()
                .filter_map(|sample| sample.context_growth_tokens.map(|value| value as f64)),
        )
    }

    /// Mean prompt length in the request window.
    pub fn average_prompt_tokens(&self) -> f64 {
        Self::average(
            self.requests
                .iter()
                .map(|sample| sample.prompt_tokens as f64),
        )
    }

    /// Mean completion length in the request window.
    pub fn average_completion_tokens(&self) -> f64 {
        Self::average(
            self.requests
                .iter()
                .map(|sample| sample.completion_tokens as f64),
        )
    }

    /// Mean end-to-end latency in the request window.
    pub fn average_e2e_seconds(&self) -> f64 {
        Self::average(self.requests.iter().map(|sample| sample.e2e_seconds))
    }

    /// Mean finite non-negative decode duration, when available.
    pub fn average_decode_seconds(&self) -> Option<f64> {
        let values = self
            .requests
            .iter()
            .filter_map(|sample| sample.decode_seconds)
            .filter(|seconds| seconds.is_finite() && *seconds >= 0.0);
        Self::optional_average(values)
    }

    /// Mean Router RequestPool residence time.
    pub fn average_queue_seconds(&self) -> f64 {
        Self::average(self.requests.iter().map(|sample| sample.queue_seconds))
    }

    /// Mean prefix-cache hit tokens in the request window.
    pub fn average_cached_prompt_tokens(&self) -> f64 {
        Self::average(
            self.requests
                .iter()
                .map(|sample| sample.cached_prompt_tokens as f64),
        )
    }

    /// Mean uncached prompt tokens in the request window.
    pub fn average_uncached_prompt_tokens(&self) -> f64 {
        Self::average(self.requests.iter().map(|sample| {
            sample
                .prompt_tokens
                .saturating_sub(sample.cached_prompt_tokens) as f64
        }))
    }

    /// Token-weighted prompt cache-hit ratio.
    pub fn average_cached_prompt_ratio(&self) -> f64 {
        let prompt_tokens = self
            .requests
            .iter()
            .map(|sample| sample.prompt_tokens)
            .sum::<usize>();
        if prompt_tokens == 0 {
            return 0.0;
        }
        let cached_tokens = self
            .requests
            .iter()
            .map(|sample| sample.cached_prompt_tokens)
            .sum::<usize>();
        cached_tokens as f64 / prompt_tokens as f64
    }

    /// Completion-rate estimate based on the first and last sample times.
    pub fn request_throughput_per_second(&self) -> f64 {
        let (Some(first), Some(last)) = (self.requests.front(), self.requests.back()) else {
            return 0.0;
        };
        if self.requests.len() < 2 {
            return 0.0;
        }
        let elapsed = last
            .finished_at
            .saturating_duration_since(first.finished_at);
        if elapsed.is_zero() {
            return 0.0;
        }
        (self.requests.len() - 1) as f64 / elapsed.as_secs_f64()
    }

    /// Mean request-level rounds elapsed since the latest TTL pause.
    pub fn average_rounds_since_ttl_pause(&self) -> f64 {
        Self::average(
            self.requests
                .iter()
                .map(|sample| sample.rounds_since_ttl_pause as f64),
        )
    }

    /// Mean cache-continuous segment length sampled at TTL pause.
    pub fn average_ttl_pause_rounds(&self) -> f64 {
        Self::average(self.ttl_pause_rounds.iter().map(|rounds| *rounds as f64))
    }

    /// Read the retained same-Program intervals without exposing mutation.
    pub fn continuity_samples(&self) -> impl Iterator<Item = ContinuitySample> + '_ {
        self.continuities.iter().copied()
    }

    /// Mean of finite values. Empty input returns zero.
    pub fn average(values: impl Iterator<Item = f64>) -> f64 {
        Self::optional_average(values).unwrap_or(0.0)
    }

    fn optional_average(values: impl Iterator<Item = f64>) -> Option<f64> {
        let (sum, count) = values.fold((0.0, 0usize), |(sum, count), value| {
            (sum + value, count + 1)
        });
        (count > 0).then(|| sum / count as f64)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    fn sample(finished_at: Instant, prompt: usize, cached: usize) -> RequestSample {
        RequestSample {
            prompt_tokens: prompt,
            completion_tokens: 10,
            cached_prompt_tokens: cached,
            context_growth_tokens: Some(20),
            e2e_seconds: 2.0,
            decode_seconds: Some(1.0),
            queue_seconds: 0.5,
            rounds_since_ttl_pause: 3,
            finished_at,
        }
    }

    #[test]
    fn bounded_windows_drop_oldest_samples() {
        let now = Instant::now();
        let mut factors = ProgressTtlFactors::default();
        factors.push_request(sample(now, 100, 25), 2);
        factors.push_request(sample(now + Duration::from_secs(1), 200, 100), 2);
        factors.push_request(sample(now + Duration::from_secs(2), 300, 225), 2);
        assert_eq!(factors.request_sample_count(), 2);
        assert_eq!(factors.average_prompt_tokens(), 250.0);
        assert_eq!(factors.average_cached_prompt_ratio(), 325.0 / 500.0);
        assert_eq!(factors.request_throughput_per_second(), 1.0);
    }

    #[test]
    fn incomplete_windows_and_empty_values_have_safe_fallbacks() {
        let mut factors = ProgressTtlFactors::default();
        factors.push_continuity(
            ContinuitySample {
                interval_seconds: 1.0,
                cache_miss_impact_seconds: 2.0,
            },
            0,
        );
        assert_eq!(factors.continuity_sample_count(), 0);
        assert!(!factors.continuity_window_complete(0));
        assert_eq!(factors.average_decode_seconds(), None);
        assert_eq!(factors.request_throughput_per_second(), 0.0);
    }

    #[test]
    fn ttl_pause_rounds_are_independent_from_request_age() {
        let now = Instant::now();
        let mut factors = ProgressTtlFactors::default();
        factors.push_request(sample(now, 100, 50), 4);
        factors.push_ttl_pause_rounds(9, 4);
        assert_eq!(factors.average_rounds_since_ttl_pause(), 3.0);
        assert_eq!(factors.average_ttl_pause_rounds(), 9.0);
    }
}
